const Router = require('express')
const router = new Router()
const authMiddleware = require('../middleware/auth.middleware')
const fileController = require('../controllers/fileController')

router.post('', authMiddleware, fileController.createDir)
router.post('/upload', authMiddleware, fileController.uploadFile)
router.post('/avatar', authMiddleware, fileController.uploadAvatar)
router.get('', authMiddleware, fileController.getFiles)
router.get('/download', authMiddleware, fileController.downloadFile)
router.get('/search', authMiddleware, fileController.searchFile)
router.delete('/', authMiddleware, fileController.deleteFile)
router.delete('/avatar', authMiddleware, fileController.deleteAvatar)
router.put('/changeemail', authMiddleware, fileController.changeEmail)
router.put('/changeusername', authMiddleware, fileController.changeUsername)
router.put('/changepassword', authMiddleware, fileController.changeUsername)
router.put('/setfavorite', authMiddleware, fileController.addToFavorite)
router.put('/sendtobin', authMiddleware, fileController.addToBin)

module.exports = router